### ISSUE TITLE
Deploy of a new release to Maven Central

### ISSUE THREAD

**Issue by dwie** [UnquietCode/JCodeModel#14]
To make use of the fix in f95f6978ce11ce36e824ef93f769ad7536d75441, I require a new release to be deployed to Maven Central. That would be great!

**Comment by UnquietCode** [comment]
@dwie The latest 1.0.3 release is currently being promoted to the sonatype central repository. Thanks for your patience.

**Comment by dwie** [comment]
That is great, thank you!
