### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by FredericHeem** [UnquietCode/JCodeModel#7]
Would it be possible to upload JCodeModel to the main maven repository ? It's safer for projects that depends on *JCodeModel*

**Comment by UnquietCode** [comment]
Yes, I'd like to see this happen as well. Per Sonatype's requirements the group name would have to change to `com.unquietcode`, which is mostly a matter of coordinating the change with my other projects.

**Comment by UnquietCode** [comment]
Now available in Maven Central under the group name `com.unquietcode.tools.jcodemodel`.
